name: Generate snake animation

on:
  schedule: # Execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:
  
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This action checks out your repository's code to the runner.
      
      - name: Generate snake.svg
        uses: Platane/snk@v3  # Use Platane/snk action to generate the snake animation.
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg  # Specify the output file path.

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add dist/snake.svg
          git commit -m "Update snake.svg"
          git push origin HEAD:${{ github.ref }}

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # Branch where you want to push the generated files.
          build_dir: dist  # Directory containing the files to deploy.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication.

